version: '2'

services:
  app:
    build: .
    image: tamplo_client_dev
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src
    container_name: client-tamplo-dev
