version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./src:/app/src
    container_name: ${DOCKER_CONTAINER_NAME}
