# DEV DockerFile
FROM node:14-alpine

ARG REACT_APP_SERVER_URL
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL

WORKDIR /app

COPY package.json package.json
COPY tsconfig.json tsconfig.json

RUN npm install

COPY src src
COPY public public

CMD npm run start